### PR TITLE
Fixed the index issue

### PR DESCRIPTION
**Pull request by dhanababum**
which will resolve the touch pinch zoom in/out issue
This issue is related to [Pinch zooming not working](https://github.com/lukebrandonfarrell/react-native-images-collage/issues/7)

### CODE REVIEW

**Comment by lukebrandonfarrell** [comment]
@dhanababum 

I've tested this fix an it give me:

screen shot 2018-12-21 at 22 45 58

React : 16.6.3
RN: 0.57.8

What versions are you running, in which this fix works for you?

**Comment by dhanababum** [comment]
I am using,
"react": "16.2.0"
"react-native": "0.52.0"

**Comment by lukebrandonfarrell** [comment]
@dhanababum 

Thanks! I'll give it a test in the next few days.

**Comment by lukebrandonfarrell** [comment]
@dhanababum 

Think we've fixed the issue. The collage component multi-touch will not work when placed in a react-native Modal component. I am going to update the README soon.

**Comment by lukebrandonfarrell** [comment]
@dhanababum Sorry my bad, this was a Android specific issue, your fixed would have worked, but only for Android. Version 3.2.1 fixes this issue by removing `undefined` from the touchBank.

Thanks for you contribution.

**Pull request closed without merging**
